services:
  - type: web
    name: aviator-backend
    env: node
    buildCommand: npm run install:prod && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true
